apiVersion: v1
kind: Service
metadata:
  name: kaboom
  labels:
    app: kaboom
spec:
  selector:
    app: kaboom
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30800
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaboom
  labels:
    app: kaboom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaboom
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: kaboom
    spec:
      containers:
        - name: kaboom
          image: mrcolorrain/kaboom:latest
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 128m
              memory: 128Mi  
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values:
                - on-prem

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kaboom
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kaboom
  minReplicas: 1
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 90
